export const teamColors = {
    "Golden State Warriors": { color: "#1d428a", abbrev: "GSW" },
    "Los Angeles Lakers": { color: "#f9a01b", abbrev: "LAL" },
    "Cleveland Cavaliers": { color: "#860038", abbrev: "CLE" },
    "Chicago Bulls": { color: "#ce1141", abbrev: "CHI" },
    "Boston Celtics": { color: "#007a33", abbrev: "BOS" },
    "Miami Heat": { color: "#98002e", abbrev: "MIA" },
    "Houston Rockets": { color: "#CE1141", abbrev: "HOU" },
    "Oklahoma City Thunder": { color: "#ef3b24", abbrev: "OKC" },
    "Milwaukee Bucks": { color: "#00471b", abbrev: "MIL" },
    "Los Angeles Clippers": { color: "#1d428a", abbrev: "LAC" },
    "San Antonio Spurs": { color: "#C4CED4", abbrev: "SAS" },
    "Brooklyn Nets": { color: "#000000", abbrev: "BKN" },
    "Philadelphia 76ers": { color: "#006BB6", abbrev: "PHI" },
    "Toronto Raptors": { color: "#a1a1a4", abbrev: "TOR" },
    "Dallas Mavericks": { color: "#00538C", abbrev: "DAL" },
    "New York Knicks": { color: "#f58426", abbrev: "NYK" },
    "Phoenix Suns": { color: "#1D1160", abbrev: "PHX" },
    "Minnesota Timberwolves": { color: "#0C2340", abbrev: "MIN" },
    "Indiana Pacers": { color: "#002D62", abbrev: "IND" },
    "Portland Trail Blazers": { color: "#E03A3E", abbrev: "POR" },
    "New Orleans Pelicans": { color: "#85714d", abbrev: "NOP" },
    "Denver Nuggets": { color: "#0E2240", abbrev: "DEN" },
    "Atlanta Hawks": { color: "#E03A3E", abbrev: "ATL" },
    "Charlotte Hornets": { color: "#00788c", abbrev: "CHA" },
    "Sacramento Kings": { color: "#5A2D81", abbrev: "SAC" },
    "Memphis Grizzlies": { color: "#5D76A9", abbrev: "MEM" },
    "Orlando Magic": { color: "#0077C0", abbrev: "ORL" },
    "Washington Wizards": { color: "#002b5c", abbrev: "WAS" },
    "Detroit Pistons": { color: "#c8102e", abbrev: "DET" },
    "Utah Jazz": { color: "#002B5C", abbrev: "UTA" }
};
